### PR TITLE
Update googletest submodule

### LINKED ISSUE #50: Update googletest
The current version used by owl fails to build on gcc 11. simply removing the version downloaded by git submodules and replacing it with latest googletest git fixes the issue.

### PR DESCRIPTION
**Pull request by WhyNotHugo**
Fixes: https://github.com/seemoo-lab/owl/issues/50

### CODE REVIEW

**Comment by PureTryOut** [comment]
Hey @WhyNotHugo, nice to see you here :smile:, any reason you removed your fork and thus closed this PR?

**Comment by WhyNotHugo** [comment]
Probably just cleaning up stale repositories. Must have forgotten about this PR.

The commit can still be grabbed and applied from https://github.com/seemoo-lab/owl/commit/d9b0beb69d0014335196162ba27f257d47086027.patch

**Comment by PureTryOut** [comment]
I know it can but I rather see it upstreamed ofc :wink:

**Comment by WhyNotHugo** [comment]
I meant to say that upstream can still use that patch freely. 

I think development is dead, last commit in 2022, bug fixes ignored for years.

**Pull request closed without merging**
